-- M2.5.3: Knowledge Base & Operations pilot bundle — SOP, Onboarding Guide, Policy Document
-- Mirrors packages/shared/src/system-templates.ts (KB_OPS_SCHEMA_FIELDS + withEssentials).

insert into templates (name, description, structure_json, is_system, is_shared, slug, metadata)
values
  (
    'SOP',
    'Purpose, scope, procedure, roles, and exceptions',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Purpose"}]},{"type":"paragraph","content":[{"type":"text","text":"Why this procedure exists and what it prevents or ensures.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[The outcome this SOP guarantees when followed.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Scope"}]},{"type":"paragraph","content":[{"type":"text","text":"Who and what this applies to — and what it explicitly excludes.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Applies to: team, system, or situation]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Does not cover: …]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Procedure"}]},{"type":"paragraph","content":[{"type":"text","text":"Numbered steps, in the exact order they should be performed.","marks":[{"type":"italic"}]}]},{"type":"orderedList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Step 1 — action and expected result]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Step 2 — action and expected result]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Step 3 — action and expected result]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Roles & Responsibilities"}]},{"type":"paragraph","content":[{"type":"text","text":"Who owns each step, and who to contact if it breaks.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Role] — [Responsibility]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Role] — [Responsibility]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Exceptions"}]},{"type":"paragraph","content":[{"type":"text","text":"Known edge cases and what to do when the standard steps don''t apply.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Situation] — [What to do instead]"}]}]}]}]}'::jsonb,
    true,
    true,
    'sop',
    '{"document_type":"sop","use_cases":["Standard operating procedures","Runbooks","Repeatable processes","Incident playbooks"],"supported_views":["wiki","dashboard"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"verification_status","field_label":"Verification status","field_type":"select","options":["verified","needs_review","outdated"],"ai_fill_enabled":true},{"field_key":"last_audited","field_label":"Last audited","field_type":"date","ai_fill_enabled":true},{"field_key":"review_cycle","field_label":"Review cycle","field_type":"select","options":["monthly","quarterly","biannual","annual"],"ai_fill_enabled":false}],"default_properties":{"status":"draft","verification_status":"needs_review"}}'::jsonb
  ),
  (
    'Onboarding Guide',
    'Welcome, first week, tools & access, and checkpoints',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Welcome"}]},{"type":"paragraph","content":[{"type":"text","text":"Set the tone — what this role owns and why it matters.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Welcome note and a one-line summary of the role''s mission.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"First Week"}]},{"type":"paragraph","content":[{"type":"text","text":"Day-by-day goals — enough structure to remove first-week anxiety.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Day 1: [Setup, intros, orientation]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Day 2–3: [Shadowing, reading, first small task]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Day 4–5: [First real contribution]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Tools & Access"}]},{"type":"paragraph","content":[{"type":"text","text":"Every account, tool, and permission needed — and who grants it.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Tool/System] — [Requested from]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Tool/System] — [Requested from]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Checkpoints"}]},{"type":"paragraph","content":[{"type":"text","text":"30/60/90-day markers so progress is visible to both sides.","marks":[{"type":"italic"}]}]},{"type":"orderedList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"30 days: [What success looks like]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"60 days: [What success looks like]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"90 days: [What success looks like]"}]}]}]}]}'::jsonb,
    true,
    true,
    'onboarding-guide',
    '{"document_type":"onboarding_guide","use_cases":["New hire onboarding","Role transitions","Team ramp-up","Contractor kickoff"],"supported_views":["wiki","calendar"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"verification_status","field_label":"Verification status","field_type":"select","options":["verified","needs_review","outdated"],"ai_fill_enabled":true},{"field_key":"last_audited","field_label":"Last audited","field_type":"date","ai_fill_enabled":true},{"field_key":"review_cycle","field_label":"Review cycle","field_type":"select","options":["monthly","quarterly","biannual","annual"],"ai_fill_enabled":false}],"default_properties":{"status":"draft","verification_status":"needs_review"}}'::jsonb
  ),
  (
    'Policy Document',
    'Statement, applicability, requirements, enforcement, and review',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Policy Statement"}]},{"type":"paragraph","content":[{"type":"text","text":"One or two sentences stating the rule — no ambiguity.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[The policy, stated plainly.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Applicability"}]},{"type":"paragraph","content":[{"type":"text","text":"Who must follow this, and any exclusions.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Applies to: team, role, or system]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Excludes: …]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Requirements"}]},{"type":"paragraph","content":[{"type":"text","text":"Concrete, checkable requirements — not intentions.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Requirement 1]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Requirement 2]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Enforcement"}]},{"type":"paragraph","content":[{"type":"text","text":"What happens when this policy isn''t followed.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Consequences and who is responsible for enforcing them.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Review"}]},{"type":"paragraph","content":[{"type":"text","text":"How often this policy is revisited, and by whom.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Review cadence and owner.]"}]}]}'::jsonb,
    true,
    true,
    'policy-document',
    '{"document_type":"policy","use_cases":["Company policies","Compliance requirements","Acceptable use","Data handling rules"],"supported_views":["wiki","dashboard"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"verification_status","field_label":"Verification status","field_type":"select","options":["verified","needs_review","outdated"],"ai_fill_enabled":true},{"field_key":"last_audited","field_label":"Last audited","field_type":"date","ai_fill_enabled":true},{"field_key":"review_cycle","field_label":"Review cycle","field_type":"select","options":["monthly","quarterly","biannual","annual"],"ai_fill_enabled":false}],"default_properties":{"status":"draft","verification_status":"needs_review"}}'::jsonb
  )
on conflict (slug) where slug is not null do update
set
  name = excluded.name,
  description = excluded.description,
  structure_json = excluded.structure_json,
  is_system = excluded.is_system,
  is_shared = excluded.is_shared,
  metadata = excluded.metadata
where templates.is_system = true and templates.workspace_id is null;
