-- M2.5.12: Academic & Scientific Research bundle — Research Paper, Thesis, Student Essay, Literature Review
-- Mirrors packages/shared/src/system-templates.ts (ACADEMIC_RESEARCH_SCHEMA_FIELDS + withEssentials).

insert into templates (name, description, structure_json, is_system, is_shared, slug, metadata)
values
  (
    'Research Paper',
    'Abstract, methodology, results, discussion, and references',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Abstract"}]},{"type":"paragraph","content":[{"type":"text","text":"The whole paper in 150-250 words — problem, method, key result.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Abstract.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Introduction"}]},{"type":"paragraph","content":[{"type":"text","text":"The gap in existing knowledge this paper addresses.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Introduction.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Methodology"}]},{"type":"paragraph","content":[{"type":"text","text":"How the research was conducted, in enough detail to replicate.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Methodology.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Results"}]},{"type":"paragraph","content":[{"type":"text","text":"What was found — data and observations, without interpretation yet.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Results.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Discussion"}]},{"type":"paragraph","content":[{"type":"text","text":"What the results mean, their limitations, and implications.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Discussion.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"References"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source cited, formatted per the target venue''s style.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Reference]"}]}]}]}]}'::jsonb,
    true,
    true,
    'research-paper',
    '{"document_type":"research_paper","use_cases":["Journal submissions","Conference papers","Preprints"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"paper_status","field_label":"Paper status","field_type":"status","options":[{"value":"drafting","label":"Drafting","category":"unstarted"},{"value":"under_review","label":"Under review","category":"started"},{"value":"revision","label":"Revision","category":"started"},{"value":"accepted","label":"Accepted","category":"completed"},{"value":"published","label":"Published","category":"completed"}],"ai_fill_enabled":true},{"field_key":"journal_or_venue","field_label":"Journal / venue","field_type":"text","ai_fill_enabled":true},{"field_key":"citation_style","field_label":"Citation style","field_type":"select","options":["apa","mla","chicago","ieee"],"ai_fill_enabled":true}],"default_properties":{"status":"draft","paper_status":"drafting"}}'::jsonb
  ),
  (
    'Thesis',
    'Abstract, research question, literature review, methodology, and findings',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Abstract"}]},{"type":"paragraph","content":[{"type":"text","text":"The thesis in miniature — question, method, and conclusion.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Abstract.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Introduction & Research Question"}]},{"type":"paragraph","content":[{"type":"text","text":"Why this question matters, and precisely what it is.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Introduction and research question.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Literature Review"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s already known, and where this thesis fits in.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Literature review.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Methodology"}]},{"type":"paragraph","content":[{"type":"text","text":"How the research question was investigated.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Methodology.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Findings"}]},{"type":"paragraph","content":[{"type":"text","text":"What the research revealed.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Findings.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Conclusion & Future Work"}]},{"type":"paragraph","content":[{"type":"text","text":"What this means, and what''s left to explore.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Conclusion and future work.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"References"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source cited.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Reference]"}]}]}]}]}'::jsonb,
    true,
    true,
    'thesis',
    '{"document_type":"thesis","use_cases":["Bachelor thesis","Master thesis","PhD dissertations"],"supported_views":["wiki","kanban","gantt"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"thesis_level","field_label":"Thesis level","field_type":"select","options":["bachelor","master","phd"],"ai_fill_enabled":true},{"field_key":"thesis_status","field_label":"Thesis status","field_type":"status","options":[{"value":"proposal","label":"Proposal","category":"unstarted"},{"value":"writing","label":"Writing","category":"started"},{"value":"review","label":"Review","category":"started"},{"value":"defense_scheduled","label":"Defense scheduled","category":"started"},{"value":"completed","label":"Completed","category":"completed"}],"ai_fill_enabled":true},{"field_key":"advisor","field_label":"Advisor","field_type":"text","ai_fill_enabled":true},{"field_key":"defense_date","field_label":"Defense date","field_type":"date","ai_fill_enabled":true},{"field_key":"citation_style","field_label":"Citation style","field_type":"select","options":["apa","mla","chicago","ieee"],"ai_fill_enabled":true}],"default_properties":{"status":"draft","thesis_level":"bachelor","thesis_status":"proposal"}}'::jsonb
  ),
  (
    'Student Essay',
    'Thesis statement, argument, counterarguments, and conclusion',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Thesis Statement"}]},{"type":"paragraph","content":[{"type":"text","text":"The single claim this essay argues for, in one sentence.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Thesis statement.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Body Paragraphs / Argument"}]},{"type":"paragraph","content":[{"type":"text","text":"Each point supporting the thesis, with evidence.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Argument and evidence.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Counterarguments"}]},{"type":"paragraph","content":[{"type":"text","text":"The strongest objection to your thesis, and your response to it.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Counterargument and response.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Conclusion"}]},{"type":"paragraph","content":[{"type":"text","text":"Restate the thesis in light of the argument, and its wider significance.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Conclusion.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"References"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source cited.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Reference]"}]}]}]}]}'::jsonb,
    true,
    true,
    'student-essay',
    '{"document_type":"student_essay","use_cases":["Coursework essays","Argumentative writing","Exam preparation"],"supported_views":["wiki","calendar"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"course","field_label":"Course","field_type":"text","ai_fill_enabled":true},{"field_key":"word_count_target","field_label":"Word count target","field_type":"number","ai_fill_enabled":false},{"field_key":"essay_status","field_label":"Essay status","field_type":"status","options":[{"value":"outline","label":"Outline","category":"unstarted"},{"value":"drafting","label":"Drafting","category":"started"},{"value":"revising","label":"Revising","category":"started"},{"value":"submitted","label":"Submitted","category":"completed"}],"ai_fill_enabled":true}],"default_properties":{"status":"draft","essay_status":"outline"}}'::jsonb
  ),
  (
    'Literature Review',
    'Sources reviewed, synthesis of themes, and gaps in the literature',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Research Question / Scope"}]},{"type":"paragraph","content":[{"type":"text","text":"What this review is trying to answer, and its boundaries.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Research question and scope.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Sources Reviewed"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source, with its key finding and relevance to your question.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Source"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Key Findings"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Relevance"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Source]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Key finding]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Relevance]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Synthesis & Themes"}]},{"type":"paragraph","content":[{"type":"text","text":"The patterns and disagreements across sources — not a list, a synthesis.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Synthesis and themes.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Gaps in Literature"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s missing — this is often where your own research question lives.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Gap]"}]}]}]}]}'::jsonb,
    true,
    true,
    'literature-review',
    '{"document_type":"literature_review","use_cases":["Thesis background chapters","Systematic reviews","Research proposals"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"research_area","field_label":"Research area","field_type":"text","ai_fill_enabled":true},{"field_key":"review_status","field_label":"Review status","field_type":"status","options":[{"value":"scoping","label":"Scoping","category":"unstarted"},{"value":"reviewing","label":"Reviewing","category":"started"},{"value":"synthesizing","label":"Synthesizing","category":"started"},{"value":"complete","label":"Complete","category":"completed"}],"ai_fill_enabled":true},{"field_key":"citation_style","field_label":"Citation style","field_type":"select","options":["apa","mla","chicago","ieee"],"ai_fill_enabled":true}],"default_properties":{"status":"draft","review_status":"scoping"}}'::jsonb
  )
on conflict (slug) where slug is not null do update
set
  name = excluded.name,
  description = excluded.description,
  structure_json = excluded.structure_json,
  is_system = excluded.is_system,
  is_shared = excluded.is_shared,
  metadata = excluded.metadata
where templates.is_system = true and templates.workspace_id is null;
