-- M2.5.7: GTM & Project Execution bundle — Project Charter, GTM Plan, Launch Checklist, Status Report
-- Mirrors packages/shared/src/system-templates.ts (GTM_PROJECT_SCHEMA_FIELDS + withEssentials).

insert into templates (name, description, structure_json, is_system, is_shared, slug, metadata)
values
  (
    'Project Charter',
    'Objective, scope, stakeholders, milestones, and success criteria',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Objective & Business Case"}]},{"type":"paragraph","content":[{"type":"text","text":"Why this project exists, and the value it delivers.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Objective and business case.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Scope"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s in scope, and — just as important — what''s explicitly out.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"In scope: [item]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Out of scope: [item]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Stakeholders & Roles"}]},{"type":"paragraph","content":[{"type":"text","text":"Who''s involved, and what they''re responsible for.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Name/Role] — [Responsibility]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Milestones"}]},{"type":"paragraph","content":[{"type":"text","text":"The key checkpoints from kickoff to completion.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Milestone"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Target Date"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Milestone]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Date]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Success Criteria"}]},{"type":"paragraph","content":[{"type":"text","text":"How you''ll know this project succeeded.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Success criterion]"}]}]}]}]}'::jsonb,
    true,
    true,
    'project-charter',
    '{"document_type":"project_charter","use_cases":["Project kickoff","Cross-functional initiatives","Stakeholder alignment"],"supported_views":["wiki","gantt","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"sponsor","field_label":"Sponsor","field_type":"text","ai_fill_enabled":true}],"default_properties":{"status":"draft"}}'::jsonb
  ),
  (
    'GTM Plan',
    'Positioning, audience, channels, and success metrics for a launch',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Positioning & Messaging"}]},{"type":"paragraph","content":[{"type":"text","text":"How this is positioned, and the core message across channels.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Positioning and key message.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Target Audience & Segments"}]},{"type":"paragraph","content":[{"type":"text","text":"Who this launch is for, segmented enough to tailor messaging.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Segment 1]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Segment 2]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Channels & Tactics"}]},{"type":"paragraph","content":[{"type":"text","text":"Where and how you''ll reach each segment.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Channel"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Tactic"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Budget"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Channel]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Tactic]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Budget]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Success Metrics & KPIs"}]},{"type":"paragraph","content":[{"type":"text","text":"How you''ll measure whether the launch worked.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Metric and target]"}]}]}]}]}'::jsonb,
    true,
    true,
    'gtm-plan',
    '{"document_type":"gtm_plan","use_cases":["Product launches","Campaign planning","Market entry"],"supported_views":["wiki","kanban","gantt","dashboard"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"gtm_status","field_label":"GTM status","field_type":"status","options":[{"value":"draft","label":"Draft","category":"unstarted"},{"value":"approved","label":"Approved","category":"unstarted"},{"value":"executing","label":"Executing","category":"started"},{"value":"complete","label":"Complete","category":"completed"}],"ai_fill_enabled":true},{"field_key":"target_launch_date","field_label":"Target launch date","field_type":"date","ai_fill_enabled":true},{"field_key":"sponsor","field_label":"Sponsor","field_type":"text","ai_fill_enabled":true}],"default_properties":{"status":"draft","gtm_status":"draft"}}'::jsonb
  ),
  (
    'Launch Checklist',
    'Readiness tasks, go/no-go criteria, and rollback plan',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Checklist"}]},{"type":"paragraph","content":[{"type":"text","text":"Every task required to launch, with an owner and current status.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Task"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Status"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Notes"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Engineering readiness]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Notes]"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Marketing readiness]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Notes]"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Support readiness]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Notes]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Go / No-Go Criteria"}]},{"type":"paragraph","content":[{"type":"text","text":"The conditions that must be true to launch.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Criterion]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Rollback Plan"}]},{"type":"paragraph","content":[{"type":"text","text":"What happens if something goes wrong after launch.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Rollback plan.]"}]}]}'::jsonb,
    true,
    true,
    'launch-checklist',
    '{"document_type":"launch_checklist","use_cases":["Product launches","Feature rollouts","Release management"],"supported_views":["kanban","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"launch_date","field_label":"Launch date","field_type":"date","ai_fill_enabled":true},{"field_key":"launch_status","field_label":"Launch status","field_type":"status","options":[{"value":"planning","label":"Planning","category":"unstarted"},{"value":"ready","label":"Ready","category":"started"},{"value":"launched","label":"Launched","category":"completed"},{"value":"rolled_back","label":"Rolled back","category":"canceled"}],"ai_fill_enabled":true}],"default_properties":{"status":"draft","launch_status":"planning"}}'::jsonb
  ),
  (
    'Status Report',
    'Summary, key metrics, wins, risks, and next steps for a reporting period',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"A short, scannable summary of where things stand.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Metrics"}]},{"type":"paragraph","content":[{"type":"text","text":"The numbers that matter this period, with trend if useful.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Metric"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"This Period"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Trend"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Metric]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Value]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[↑/↓/→]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Wins"}]},{"type":"paragraph","content":[{"type":"text","text":"What went well since the last report.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Win]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Risks & Blockers"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s at risk, and what''s blocking progress.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Risk or blocker]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Steps"}]},{"type":"paragraph","content":[{"type":"text","text":"What happens between now and the next report.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Next step]"}]}]}]}]}'::jsonb,
    true,
    true,
    'weekly-status',
    '{"document_type":"weekly_status","use_cases":["Status updates","Stakeholder reporting","Project health checks"],"supported_views":["dashboard","calendar","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"report_period","field_label":"Report period","field_type":"text","ai_fill_enabled":true},{"field_key":"health","field_label":"Health","field_type":"status","options":[{"value":"on_track","label":"On track","category":"started"},{"value":"at_risk","label":"At risk","category":"started"},{"value":"off_track","label":"Off track","category":"started"}],"ai_fill_enabled":true}],"default_properties":{"status":"draft","health":"on_track"}}'::jsonb
  )
on conflict (slug) where slug is not null do update
set
  name = excluded.name,
  description = excluded.description,
  structure_json = excluded.structure_json,
  is_system = excluded.is_system,
  is_shared = excluded.is_shared,
  metadata = excluded.metadata
where templates.is_system = true and templates.workspace_id is null;
