-- M2.5.8: Content & Campaign Marketing bundle — Campaign Brief, Content Calendar Item, SEO Brief, Social Post Batch
-- Mirrors packages/shared/src/system-templates.ts (CONTENT_MARKETING_SCHEMA_FIELDS + withEssentials).

insert into templates (name, description, structure_json, is_system, is_shared, slug, metadata)
values
  (
    'Campaign Brief',
    'Objective, audience, channels, timeline, and success metrics for a campaign',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Objective & Audience"}]},{"type":"paragraph","content":[{"type":"text","text":"What this campaign is trying to achieve, and for whom.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Objective and target audience.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Message"}]},{"type":"paragraph","content":[{"type":"text","text":"The single message every asset should reinforce.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Key message.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Channels & Timeline"}]},{"type":"paragraph","content":[{"type":"text","text":"Where this runs, and when each phase happens.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Channel"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Phase"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Timing"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Channel]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Phase]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Dates]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Success Metrics"}]},{"type":"paragraph","content":[{"type":"text","text":"How you''ll know the campaign worked.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Metric and target]"}]}]}]}]}'::jsonb,
    true,
    true,
    'campaign-brief',
    '{"document_type":"campaign_brief","use_cases":["Marketing campaigns","Product launches","Brand initiatives"],"supported_views":["wiki","kanban","gantt","dashboard"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"campaign_status","field_label":"Campaign status","field_type":"status","options":[{"value":"planning","label":"Planning","category":"unstarted"},{"value":"live","label":"Live","category":"started"},{"value":"complete","label":"Complete","category":"completed"}],"ai_fill_enabled":true},{"field_key":"channel","field_label":"Channel","field_type":"multi_select","options":["email","social","paid","organic","pr"],"ai_fill_enabled":true},{"field_key":"budget","field_label":"Budget","field_type":"number","ai_fill_enabled":false}],"default_properties":{"status":"draft","campaign_status":"planning"}}'::jsonb
  ),
  (
    'Content Calendar Item',
    'Brief, outline, SEO keywords, and distribution for a single piece of content',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Brief & Angle"}]},{"type":"paragraph","content":[{"type":"text","text":"What this piece is about, and the unique angle it takes.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Brief and angle.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Outline"}]},{"type":"paragraph","content":[{"type":"text","text":"The structure this piece will follow.","marks":[{"type":"italic"}]}]},{"type":"orderedList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Section 1]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Section 2]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Section 3]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"SEO Keywords"}]},{"type":"paragraph","content":[{"type":"text","text":"Primary and secondary keywords this piece should rank for.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Primary keyword]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Secondary keyword]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Distribution Channels"}]},{"type":"paragraph","content":[{"type":"text","text":"Where this gets published and promoted.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Channel]"}]}]}]}]}'::jsonb,
    true,
    true,
    'editorial-calendar',
    '{"document_type":"editorial_calendar","use_cases":["Blog posts","Newsletters","Video/podcast planning"],"supported_views":["calendar","kanban","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"publish_date","field_label":"Publish date","field_type":"date","ai_fill_enabled":true},{"field_key":"content_status","field_label":"Content status","field_type":"status","options":[{"value":"idea","label":"Idea","category":"unstarted"},{"value":"drafting","label":"Drafting","category":"started"},{"value":"review","label":"Review","category":"started"},{"value":"scheduled","label":"Scheduled","category":"started"},{"value":"published","label":"Published","category":"completed"}],"ai_fill_enabled":true},{"field_key":"content_type","field_label":"Content type","field_type":"select","options":["blog","video","social","newsletter","podcast"],"ai_fill_enabled":true},{"field_key":"campaign","field_label":"Campaign","field_type":"relation","ai_fill_enabled":false}],"default_properties":{"status":"draft","content_status":"idea"}}'::jsonb
  ),
  (
    'SEO Brief',
    'Target keyword, search intent, competing pages, and content outline',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Target Keyword & Search Intent"}]},{"type":"paragraph","content":[{"type":"text","text":"The keyword this page targets, and what the searcher actually wants.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Target keyword and search intent.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Competing Pages"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s currently ranking, and what it does well or poorly.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"URL"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Word Count"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Notes"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Competing URL]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Word count]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Notes]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Content Outline"}]},{"type":"paragraph","content":[{"type":"text","text":"The heading structure that will satisfy search intent.","marks":[{"type":"italic"}]}]},{"type":"orderedList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[H2 section]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[H2 section]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[H2 section]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Internal Linking Plan"}]},{"type":"paragraph","content":[{"type":"text","text":"Which existing pages should link to this, and vice versa.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Page to link from/to]"}]}]}]}]}'::jsonb,
    true,
    true,
    'seo-brief',
    '{"document_type":"seo_brief","use_cases":["SEO content","Page optimization","Content strategy"],"supported_views":["kanban","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"target_keyword","field_label":"Target keyword","field_type":"text","ai_fill_enabled":true},{"field_key":"search_intent","field_label":"Search intent","field_type":"select","options":["informational","navigational","transactional","commercial"],"ai_fill_enabled":true},{"field_key":"seo_status","field_label":"SEO status","field_type":"status","options":[{"value":"research","label":"Research","category":"unstarted"},{"value":"drafting","label":"Drafting","category":"started"},{"value":"optimizing","label":"Optimizing","category":"started"},{"value":"published","label":"Published","category":"completed"}],"ai_fill_enabled":true},{"field_key":"campaign","field_label":"Campaign","field_type":"relation","ai_fill_enabled":false}],"default_properties":{"status":"draft","seo_status":"research"}}'::jsonb
  ),
  (
    'Social Post Batch',
    'A batch of scheduled posts across platforms, with copy and performance notes',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Posts"}]},{"type":"paragraph","content":[{"type":"text","text":"Every post in this batch, with copy, platform, and schedule.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Post"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Platform"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Copy"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Scheduled Date"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Status"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Post 1]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Platform]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Copy]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Date]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Hashtags & Mentions"}]},{"type":"paragraph","content":[{"type":"text","text":"Reusable hashtags and accounts to tag across this batch.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[#hashtag]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[@mention]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Performance Notes"}]},{"type":"paragraph","content":[{"type":"text","text":"What worked, what didn''t — feed this into the next batch.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Performance notes.]"}]}]}'::jsonb,
    true,
    true,
    'social-post-batch',
    '{"document_type":"social_post_batch","use_cases":["Social media scheduling","Campaign amplification","Community management"],"supported_views":["calendar","kanban","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"platform","field_label":"Platform","field_type":"multi_select","options":["instagram","tiktok","x","linkedin","facebook","youtube"],"ai_fill_enabled":true},{"field_key":"batch_status","field_label":"Batch status","field_type":"status","options":[{"value":"planning","label":"Planning","category":"unstarted"},{"value":"drafting","label":"Drafting","category":"started"},{"value":"scheduled","label":"Scheduled","category":"started"},{"value":"posted","label":"Posted","category":"completed"}],"ai_fill_enabled":true},{"field_key":"campaign","field_label":"Campaign","field_type":"relation","ai_fill_enabled":false}],"default_properties":{"status":"draft","batch_status":"planning"}}'::jsonb
  )
on conflict (slug) where slug is not null do update
set
  name = excluded.name,
  description = excluded.description,
  structure_json = excluded.structure_json,
  is_system = excluded.is_system,
  is_shared = excluded.is_shared,
  metadata = excluded.metadata
where templates.is_system = true and templates.workspace_id is null;
