-- M2.5.10: People Operations & HR bundle — 1:1 Notes, Personal Development Plan, Job Description, Performance Review
-- Mirrors packages/shared/src/system-templates.ts (PEOPLE_OPS_SCHEMA_FIELDS + withEssentials).

insert into templates (name, description, structure_json, is_system, is_shared, slug, metadata)
values
  (
    '1:1 Notes',
    'Check-in, topics discussed, action items, and notes for next time',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Check-in & General Well-being"}]},{"type":"paragraph","content":[{"type":"text","text":"How things are going, beyond the task list — start here, not with status.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Check-in notes.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Topics Discussed"}]},{"type":"paragraph","content":[{"type":"text","text":"Whatever came up — career, blockers, feedback, or anything else.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Topic]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Action Items"}]},{"type":"paragraph","content":[{"type":"text","text":"Concrete follow-ups from this conversation, with an owner and due date.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Task"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Due Date"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Status"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Task]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Date]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Notes for Next Meeting"}]},{"type":"paragraph","content":[{"type":"text","text":"What to pick back up next time.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Notes for next meeting.]"}]}]}'::jsonb,
    true,
    true,
    'one-on-one-notes',
    '{"document_type":"one_on_one_notes","use_cases":["Manager 1:1s","Skip-levels","Mentor check-ins"],"supported_views":["calendar","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"meeting_date","field_label":"Meeting date","field_type":"date","ai_fill_enabled":true},{"field_key":"participant","field_label":"Participant","field_type":"text","ai_fill_enabled":true},{"field_key":"manager","field_label":"Manager","field_type":"text","ai_fill_enabled":true},{"field_key":"requires_hr_followup","field_label":"Requires HR follow-up","field_type":"checkbox","ai_fill_enabled":false}],"default_properties":{"status":"draft"}}'::jsonb
  ),
  (
    'Personal Development Plan',
    'Career goals, skill development areas, and a check-in schedule',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Career Goals"}]},{"type":"paragraph","content":[{"type":"text","text":"Where this person wants to grow, in their own words.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Career goals.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Development Areas"}]},{"type":"paragraph","content":[{"type":"text","text":"The specific skills or competencies to build, with a concrete action per area.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Skill / Competency"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Current Level"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Target Level"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Action"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Skill]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Current]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Target]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Action]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Support Needed"}]},{"type":"paragraph","content":[{"type":"text","text":"What has to be true — budget, mentorship, time — for this plan to work.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Support needed]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Check-in Schedule"}]},{"type":"paragraph","content":[{"type":"text","text":"When you''ll revisit this plan together.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Check-in cadence.]"}]}]}'::jsonb,
    true,
    true,
    'personal-development-plan',
    '{"document_type":"personal_development_plan","use_cases":["Career development","Performance coaching","Skill growth planning"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"pdp_status","field_label":"Plan status","field_type":"status","options":[{"value":"draft","label":"Draft","category":"unstarted"},{"value":"active","label":"Active","category":"started"},{"value":"completed","label":"Completed","category":"completed"}],"ai_fill_enabled":true},{"field_key":"employee","field_label":"Employee","field_type":"text","ai_fill_enabled":true},{"field_key":"review_period","field_label":"Review period","field_type":"text","ai_fill_enabled":false}],"default_properties":{"status":"draft","pdp_status":"draft"}}'::jsonb
  ),
  (
    'Job Description',
    'Role summary, responsibilities, requirements, and compensation',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Role Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"What this role owns, and why it exists, in two or three sentences.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Role summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Responsibilities"}]},{"type":"paragraph","content":[{"type":"text","text":"What this person will actually do, day to day.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Responsibility]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Requirements"}]},{"type":"paragraph","content":[{"type":"text","text":"The must-haves — keep this list short and genuinely required.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Requirement]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Nice to Have"}]},{"type":"paragraph","content":[{"type":"text","text":"Not required, but a plus.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Nice to have]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Compensation & Benefits"}]},{"type":"paragraph","content":[{"type":"text","text":"Salary range and key benefits, where you can share them.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Compensation and benefits.]"}]}]}'::jsonb,
    true,
    true,
    'job-description',
    '{"document_type":"job_description","use_cases":["Hiring","Role definition","Org design"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"department","field_label":"Department","field_type":"text","ai_fill_enabled":true},{"field_key":"seniority","field_label":"Seniority","field_type":"select","options":["junior","mid","senior","lead","principal"],"ai_fill_enabled":true},{"field_key":"employment_type","field_label":"Employment type","field_type":"select","options":["full_time","part_time","contract","intern"],"ai_fill_enabled":true}],"default_properties":{"status":"draft"}}'::jsonb
  ),
  (
    'Performance Review',
    'Summary, goals and achievements, strengths, growth areas, and next-period goals',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"The overall takeaway — lead with this, not the details.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Goals & Achievements"}]},{"type":"paragraph","content":[{"type":"text","text":"What was agreed on this period, and how it went.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Goal"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Result"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Rating"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Goal]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Result]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Exceeds/Meets/Below]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Strengths"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s working well — be specific, not generic.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Strength]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Areas for Growth"}]},{"type":"paragraph","content":[{"type":"text","text":"What would make the next period even better.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Area for growth]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Period Goals"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s agreed for the upcoming period.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Goal]"}]}]}]}]}'::jsonb,
    true,
    true,
    'performance-review',
    '{"document_type":"performance_review","use_cases":["Performance cycles","Promotion cases","Manager feedback"],"supported_views":["wiki","kanban","calendar"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"review_status","field_label":"Review status","field_type":"status","options":[{"value":"self_review","label":"Self review","category":"started"},{"value":"manager_review","label":"Manager review","category":"started"},{"value":"calibration","label":"Calibration","category":"started"},{"value":"finalized","label":"Finalized","category":"completed"}],"ai_fill_enabled":true},{"field_key":"rating","field_label":"Overall rating","field_type":"select","options":["exceeds","meets","below","unsatisfactory"],"ai_fill_enabled":false},{"field_key":"employee","field_label":"Employee","field_type":"text","ai_fill_enabled":true},{"field_key":"review_period","field_label":"Review period","field_type":"text","ai_fill_enabled":false}],"default_properties":{"status":"draft","review_status":"self_review"}}'::jsonb
  )
on conflict (slug) where slug is not null do update
set
  name = excluded.name,
  description = excluded.description,
  structure_json = excluded.structure_json,
  is_system = excluded.is_system,
  is_shared = excluded.is_shared,
  metadata = excluded.metadata
where templates.is_system = true and templates.workspace_id is null;
