-- M2.5.11: Legal, Compliance & Finance bundle — Legal Document, Contract Review, Compliance Checklist, Financial Report
-- Mirrors packages/shared/src/system-templates.ts (LEGAL_FINANCE_SCHEMA_FIELDS + withEssentials).

insert into templates (name, description, structure_json, is_system, is_shared, slug, metadata)
values
  (
    'Legal Document',
    'Parties, terms, obligations, and signatures for a formal legal document',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Parties"}]},{"type":"paragraph","content":[{"type":"text","text":"Who is bound by this document, with full legal names.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party A]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party B]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Terms & Conditions"}]},{"type":"paragraph","content":[{"type":"text","text":"The substantive terms both parties are agreeing to.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Terms and conditions.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Obligations"}]},{"type":"paragraph","content":[{"type":"text","text":"What each party is responsible for delivering or doing.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party A obligation]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party B obligation]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Signatures"}]},{"type":"paragraph","content":[{"type":"text","text":"Signature blocks for each party, with date.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Signature blocks.]"}]}]}'::jsonb,
    true,
    true,
    'legal-document',
    '{"document_type":"legal_document","use_cases":["Agreements","NDAs","Formal legal correspondence"],"supported_views":["wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"effective_date","field_label":"Effective date","field_type":"date","ai_fill_enabled":true},{"field_key":"legal_status","field_label":"Legal status","field_type":"status","options":[{"value":"draft","label":"Draft","category":"unstarted"},{"value":"under_review","label":"Under review","category":"started"},{"value":"executed","label":"Executed","category":"completed"},{"value":"expired","label":"Expired","category":"canceled"}],"ai_fill_enabled":true},{"field_key":"jurisdiction","field_label":"Jurisdiction","field_type":"text","ai_fill_enabled":true}],"default_properties":{"status":"draft","legal_status":"draft"}}'::jsonb
  ),
  (
    'Contract Review',
    'Contract summary, key terms, risks, and a review recommendation',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Contract Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"What this contract is for, and who the counterparty is.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Contract summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Terms"}]},{"type":"paragraph","content":[{"type":"text","text":"The terms that matter most, with a clause reference for each.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Term"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Clause Reference"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Notes"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Term]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Clause]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Notes]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Risks & Redlines"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s risky as written, and what you''d want changed.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Risk or redline]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Recommendation"}]},{"type":"paragraph","content":[{"type":"text","text":"Approve, negotiate, or reject — and why.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Recommendation.]"}]}]}'::jsonb,
    true,
    true,
    'contract-review',
    '{"document_type":"contract_review","use_cases":["Vendor contracts","Customer agreements","Legal review workflows"],"supported_views":["kanban","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"counterparty","field_label":"Counterparty","field_type":"text","ai_fill_enabled":true},{"field_key":"contract_value","field_label":"Contract value","field_type":"number","ai_fill_enabled":false},{"field_key":"renewal_date","field_label":"Renewal date","field_type":"date","ai_fill_enabled":true},{"field_key":"review_status","field_label":"Review status","field_type":"status","options":[{"value":"intake","label":"Intake","category":"unstarted"},{"value":"legal_review","label":"Legal review","category":"started"},{"value":"negotiation","label":"Negotiation","category":"started"},{"value":"approved","label":"Approved","category":"completed"},{"value":"rejected","label":"Rejected","category":"canceled"}],"ai_fill_enabled":true},{"field_key":"jurisdiction","field_label":"Jurisdiction","field_type":"text","ai_fill_enabled":true}],"default_properties":{"status":"draft","review_status":"intake"}}'::jsonb
  ),
  (
    'Compliance Checklist',
    'Requirements, evidence, and a remediation plan for a compliance framework',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Requirements"}]},{"type":"paragraph","content":[{"type":"text","text":"Every requirement under this framework, with an owner and evidence.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Requirement"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Evidence"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Status"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Requirement]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Evidence]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Gaps & Remediation Plan"}]},{"type":"paragraph","content":[{"type":"text","text":"Where you''re not yet compliant, and the plan to close the gap.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Gap] — [Remediation plan]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Audit Date"}]},{"type":"paragraph","content":[{"type":"text","text":"When this needs to be reassessed.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Next audit date.]"}]}]}'::jsonb,
    true,
    true,
    'compliance-checklist',
    '{"document_type":"compliance_checklist","use_cases":["Regulatory compliance","Security certifications","Internal audits"],"supported_views":["kanban","wiki","dashboard"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"framework","field_label":"Framework","field_type":"select","options":["gdpr","soc2","hipaa","iso27001","pci_dss","other"],"ai_fill_enabled":true},{"field_key":"compliance_status","field_label":"Compliance status","field_type":"status","options":[{"value":"not_started","label":"Not started","category":"unstarted"},{"value":"in_progress","label":"In progress","category":"started"},{"value":"compliant","label":"Compliant","category":"completed"},{"value":"non_compliant","label":"Non-compliant","category":"canceled"}],"ai_fill_enabled":true}],"default_properties":{"status":"draft","compliance_status":"not_started"}}'::jsonb
  ),
  (
    'Financial Report',
    'Summary, key figures with variance, and outlook for a reporting period',
    '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"The headline story of this period''s numbers.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Figures"}]},{"type":"paragraph","content":[{"type":"text","text":"This period vs. last, with the variance called out explicitly.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Line Item"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"This Period"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Last Period"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Variance"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Line item]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Value]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Value]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[+/- %]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Notable Variances"}]},{"type":"paragraph","content":[{"type":"text","text":"Anything that moved more than expected, and why.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Variance and explanation]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Outlook"}]},{"type":"paragraph","content":[{"type":"text","text":"What you expect next period, and any risks to that outlook.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Outlook.]"}]}]}'::jsonb,
    true,
    true,
    'financial-report',
    '{"document_type":"financial_report","use_cases":["Board reporting","Investor updates","Internal finance reviews"],"supported_views":["dashboard","calendar","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"report_period","field_label":"Report period","field_type":"text","ai_fill_enabled":true},{"field_key":"report_type","field_label":"Report type","field_type":"select","options":["p_and_l","balance_sheet","cash_flow","budget_vs_actual"],"ai_fill_enabled":true},{"field_key":"currency","field_label":"Currency","field_type":"text","ai_fill_enabled":false}],"default_properties":{"status":"draft"}}'::jsonb
  )
on conflict (slug) where slug is not null do update
set
  name = excluded.name,
  description = excluded.description,
  structure_json = excluded.structure_json,
  is_system = excluded.is_system,
  is_shared = excluded.is_shared,
  metadata = excluded.metadata
where templates.is_system = true and templates.workspace_id is null;
