-- Reviewer feedback: People Ops, Legal/Finance, Academic + Ticket essentials template (Rhodes).

update templates
set
  name = 'Professional Business Letter',
  description = 'Subject, salutation, body, and closing for a formal business letter',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Salutation & Opening"}]},{"type":"paragraph","content":[{"type":"text","text":"Who you''re addressing, and the reason for writing, stated up front (BLUF).","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Dear ..., I am writing to ...]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Body"}]},{"type":"paragraph","content":[{"type":"text","text":"The substance — context, details, and requests. Use bullet lists for proposals, terms, or numbered demands.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Body of the letter.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Closing & Signature"}]},{"type":"paragraph","content":[{"type":"text","text":"Clear next step, formal sign-off, and list any attached documents or enclosures here.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Sincerely, / Best regards,]"}]},{"type":"paragraph","content":[{"type":"text","text":"Enclosures: [none / list]"}]}]}'::jsonb,
  metadata = '{"document_type":"professional_business_letter","category":"professional","use_cases":["Cover letters","Client proposals","Formal notices and references"],"supported_views":["wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"letter_type","field_label":"Letter type","field_type":"select","options":["cover_letter","reference","proposal","complaint","notice"],"ai_fill_enabled":true},{"field_key":"subject_line","field_label":"Subject line","field_type":"text","ai_fill_enabled":true},{"field_key":"recipient","field_label":"Recipient","field_type":"relation","ai_fill_enabled":false}],"default_properties":{"status":"draft"}}'::jsonb
where slug = 'professional-business-letter'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = '1:1 Notes',
  description = 'Check-in, topics discussed, action items, and notes for next time',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Check-in & General Well-being"}]},{"type":"paragraph","content":[{"type":"text","text":"How things are going, beyond the task list — start here, not with status.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Check-in notes.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Topics Discussed"}]},{"type":"paragraph","content":[{"type":"text","text":"Is this just a status update, or are we discussing career growth? Touch long-term goals regularly.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Topic]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Action Items"}]},{"type":"paragraph","content":[{"type":"text","text":"Concrete follow-ups from this conversation, with an owner and due date.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Task"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Due Date"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Status"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Task]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Date]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Notes for Next Meeting"}]},{"type":"paragraph","content":[{"type":"text","text":"What to pick back up next time — Rhodes can seed the next 1:1 from this section.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Notes for next meeting.]"}]}]}'::jsonb,
  metadata = '{"document_type":"one_on_one_notes","category":"operations","use_cases":["Manager 1:1s","Skip-levels","Mentor check-ins"],"supported_views":["calendar","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"meeting_date","field_label":"Meeting date","field_type":"date","ai_fill_enabled":true},{"field_key":"participant","field_label":"Participant","field_type":"relation","ai_fill_enabled":false},{"field_key":"manager","field_label":"Manager","field_type":"relation","ai_fill_enabled":false},{"field_key":"requires_hr_followup","field_label":"Requires HR follow-up","field_type":"checkbox","ai_fill_enabled":false},{"field_key":"visibility","field_label":"Visibility","field_type":"select","options":["private","managers","hr"],"ai_fill_enabled":false}],"default_properties":{"status":"draft","visibility":"private"}}'::jsonb
where slug = 'one-on-one-notes'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Personal Development Plan',
  description = 'Career goals, skill development areas, and a check-in schedule',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Career Goals"}]},{"type":"paragraph","content":[{"type":"text","text":"Where this person wants to grow. Link each goal to a real project — which ab-experiment or product-feature will they lead next quarter to prove the skill?","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Career goals.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Development Areas"}]},{"type":"paragraph","content":[{"type":"text","text":"Reference internal skill / role frameworks (e.g. Lead Experience Architect, Senior Fullstack Architect, Strategic Product Leadership). Make Target Level measurable.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Skill / Competency"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Current Level"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Target Level"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Action"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Skill]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Current]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Target]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Action]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Support Needed"}]},{"type":"paragraph","content":[{"type":"text","text":"What has to be true — budget, mentorship, time — for this plan to work.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Support needed]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Check-in Schedule"}]},{"type":"paragraph","content":[{"type":"text","text":"When you''ll revisit this plan together (e.g. every 3 months).","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Check-in cadence.]"}]}]}'::jsonb,
  metadata = '{"document_type":"personal_development_plan","category":"operations","use_cases":["Career development","Performance coaching","Skill growth planning"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"pdp_status","field_label":"Plan status","field_type":"status","options":[{"value":"draft","label":"Draft","category":"unstarted"},{"value":"active","label":"Active","category":"started"},{"value":"completed","label":"Completed","category":"completed"}],"ai_fill_enabled":true},{"field_key":"employee","field_label":"Employee","field_type":"relation","ai_fill_enabled":false},{"field_key":"manager","field_label":"Manager","field_type":"relation","ai_fill_enabled":false},{"field_key":"review_period","field_label":"Review period","field_type":"text","ai_fill_enabled":false}],"default_properties":{"status":"draft","pdp_status":"draft"}}'::jsonb
where slug = 'personal-development-plan'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Job Description',
  description = 'Role summary, responsibilities, requirements, and compensation',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Role Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"What this role owns, and why it exists, in two or three sentences.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Role summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Responsibilities"}]},{"type":"paragraph","content":[{"type":"text","text":"Day-to-day ownership. Include measurable impact — experiments owned, KPIs owned — not only task lists. Link skill frameworks where helpful.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Responsibility]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Requirements"}]},{"type":"paragraph","content":[{"type":"text","text":"Must-haves only. Link internal skill docs or expectation frameworks so candidates and hiring managers share one standard.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Requirement]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Nice to Have"}]},{"type":"paragraph","content":[{"type":"text","text":"Not required, but a plus.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Nice to have]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Compensation & Benefits"}]},{"type":"paragraph","content":[{"type":"text","text":"Salary range and key benefits, where you can share them.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Compensation and benefits.]"}]}]}'::jsonb,
  metadata = '{"document_type":"job_description","category":"operations","use_cases":["Hiring","Role definition","Org design"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"department","field_label":"Department","field_type":"select","options":["engineering","product","marketing","operations","leadership","other"],"ai_fill_enabled":true},{"field_key":"seniority","field_label":"Seniority","field_type":"select","options":["junior","mid","senior","lead","principal"],"ai_fill_enabled":true},{"field_key":"employment_type","field_label":"Employment type","field_type":"select","options":["full_time","part_time","contract","intern"],"ai_fill_enabled":true}],"default_properties":{"status":"draft"}}'::jsonb
where slug = 'job-description'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Performance Review',
  description = 'Summary, goals and achievements, strengths, growth areas, and next-period goals',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"The overall takeaway — lead with this, not the details.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Goals & Achievements"}]},{"type":"paragraph","content":[{"type":"text","text":"What was agreed this period, and how it went. Link shipped product-features or ab-experiments as evidence.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Goal"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Result"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Rating"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Goal]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Result]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Exceeds / Meets / Needs development]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Strengths"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s working well — be specific, not generic.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Strength]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Areas for Growth"}]},{"type":"paragraph","content":[{"type":"text","text":"What would make the next period better. Sync these insights into the employee''s personal-development-plan.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Area for growth]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Period Goals"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s agreed for the upcoming period — mirror into the PDP so review and growth stay linked.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Goal]"}]}]}]}]}'::jsonb,
  metadata = '{"document_type":"performance_review","category":"operations","use_cases":["Performance cycles","Promotion cases","Manager feedback"],"supported_views":["wiki","kanban","calendar"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"review_status","field_label":"Review status","field_type":"status","options":[{"value":"self_review","label":"Self review","category":"started"},{"value":"manager_review","label":"Manager review","category":"started"},{"value":"calibration","label":"Calibration","category":"started"},{"value":"finalized","label":"Finalized","category":"completed"}],"ai_fill_enabled":true},{"field_key":"rating","field_label":"Overall rating","field_type":"select","options":["exceeds_expectations","meets_expectations","needs_development","unsatisfactory"],"ai_fill_enabled":false},{"field_key":"employee","field_label":"Employee","field_type":"relation","ai_fill_enabled":false},{"field_key":"manager","field_label":"Manager","field_type":"relation","ai_fill_enabled":false},{"field_key":"review_period","field_label":"Review period","field_type":"text","ai_fill_enabled":false}],"default_properties":{"status":"draft","review_status":"self_review"}}'::jsonb
where slug = 'performance-review'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Legal Document',
  description = 'Parties, terms, obligations, termination, and signatures',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Parties"}]},{"type":"paragraph","content":[{"type":"text","text":"Who is bound by this document, with full legal names. Set Counterparty in Properties.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party A]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party B]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Terms & Conditions"}]},{"type":"paragraph","content":[{"type":"text","text":"Substantive terms both parties agree to. Ensure boilerplate and indemnities are reviewed by qualified counsel before execution.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Terms and conditions.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Obligations"}]},{"type":"paragraph","content":[{"type":"text","text":"What each party must deliver or do, and by when.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party A obligation]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Party B obligation]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Term, Termination & Renewal"}]},{"type":"paragraph","content":[{"type":"text","text":"Initial term, notice periods, auto-renewal, and exit rights — missing this is how evergreen traps happen.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Term, termination, and renewal.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Signatures"}]},{"type":"paragraph","content":[{"type":"text","text":"Signature blocks for each party, with date.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Signature blocks.]"}]}]}'::jsonb,
  metadata = '{"document_type":"legal_document","category":"professional","use_cases":["Agreements","NDAs","Formal legal correspondence"],"supported_views":["wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"effective_date","field_label":"Effective date","field_type":"date","ai_fill_enabled":true},{"field_key":"legal_status","field_label":"Legal status","field_type":"status","options":[{"value":"draft","label":"Draft","category":"unstarted"},{"value":"under_review","label":"Under review","category":"started"},{"value":"executed","label":"Executed","category":"completed"},{"value":"expired","label":"Expired","category":"canceled"}],"ai_fill_enabled":true},{"field_key":"jurisdiction","field_label":"Jurisdiction","field_type":"select","options":["DE","EU","US","UK","other"],"ai_fill_enabled":true},{"field_key":"counterparty","field_label":"Counterparty","field_type":"relation","ai_fill_enabled":false}],"default_properties":{"status":"draft","legal_status":"draft"}}'::jsonb
where slug = 'legal-document'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Contract Review',
  description = 'Contract summary, key terms, risks, and a review recommendation',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Contract Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"What this contract is for and who the counterparty is. Link or attach the raw PDF / source document here.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Contract summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Terms"}]},{"type":"paragraph","content":[{"type":"text","text":"Terms that matter most, with clause refs. Explicitly cover Liability, Indemnity, IP, and Data Privacy (GDPR/DSGVO).","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Term"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Clause Reference"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Notes"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Term]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Clause]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Notes]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Risks & Redlines"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s risky as written, and what you''d want changed.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Risk or redline]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Recommendation"}]},{"type":"paragraph","content":[{"type":"text","text":"Approve, negotiate, or reject — and why.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Recommendation.]"}]}]}'::jsonb,
  metadata = '{"document_type":"contract_review","category":"professional","use_cases":["Vendor contracts","Customer agreements","Legal review workflows"],"supported_views":["kanban","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"contract_value","field_label":"Contract value","field_type":"number","options":{"unit":"currency"},"ai_fill_enabled":false},{"field_key":"renewal_date","field_label":"Renewal date","field_type":"date","ai_fill_enabled":true},{"field_key":"review_status","field_label":"Review status","field_type":"status","options":[{"value":"intake","label":"Intake","category":"unstarted"},{"value":"legal_review","label":"Legal review","category":"started"},{"value":"negotiation","label":"Negotiation","category":"started"},{"value":"approved","label":"Approved","category":"completed"},{"value":"rejected","label":"Rejected","category":"canceled"}],"ai_fill_enabled":true},{"field_key":"jurisdiction","field_label":"Jurisdiction","field_type":"select","options":["DE","EU","US","UK","other"],"ai_fill_enabled":true},{"field_key":"counterparty","field_label":"Counterparty","field_type":"relation","ai_fill_enabled":false}],"default_properties":{"status":"draft","review_status":"intake"}}'::jsonb
where slug = 'contract-review'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Compliance Checklist',
  description = 'Requirements, evidence, and a remediation plan for a compliance framework',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Requirements"}]},{"type":"paragraph","content":[{"type":"text","text":"Every requirement under this framework, with owner and evidence. Link policies, SOPs, GitHub PRs, or infra configs that serve as audit evidence.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Requirement"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Owner"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Evidence"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Status"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Requirement]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Owner]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Evidence]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Not started]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Gaps & Remediation Plan"}]},{"type":"paragraph","content":[{"type":"text","text":"Where you''re not yet compliant. Each gap needs an owner and a due date — align the document Due property with the soonest remediation deadline.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Gap] — Owner: […] — Due: […] — Plan: […]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Next Audit Date"}]},{"type":"paragraph","content":[{"type":"text","text":"When this needs to be reassessed.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Next audit date.]"}]}]}'::jsonb,
  metadata = '{"document_type":"compliance_checklist","category":"professional","use_cases":["Regulatory compliance","Security certifications","Internal audits"],"supported_views":["kanban","wiki","dashboard"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"framework","field_label":"Framework","field_type":"select","options":["gdpr","soc2","hipaa","iso27001","pci_dss","other"],"ai_fill_enabled":true},{"field_key":"compliance_status","field_label":"Compliance status","field_type":"status","options":[{"value":"not_started","label":"Not started","category":"unstarted"},{"value":"in_progress","label":"In progress","category":"started"},{"value":"compliant","label":"Compliant","category":"completed"},{"value":"non_compliant","label":"Non-compliant","category":"canceled"}],"ai_fill_enabled":true},{"field_key":"related_audit","field_label":"Related audit","field_type":"relation","ai_fill_enabled":false}],"default_properties":{"status":"draft","compliance_status":"not_started"}}'::jsonb
where slug = 'compliance-checklist'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Financial Report',
  description = 'Summary, key figures with variance, and outlook for a reporting period',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Summary"}]},{"type":"paragraph","content":[{"type":"text","text":"The headline story of this period''s numbers — lead with the takeaway for CFO / investors. Set Report period as Q3-2026 or M08-2026 for sortable dashboards.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Summary.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Figures"}]},{"type":"paragraph","content":[{"type":"text","text":"This period vs. last, with variance. Link the original business-plan or department budgets as the approved baseline.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Line Item"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"This Period"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Last Period"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Variance"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Line item]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Value]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Value]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[+/- %]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Notable Variances"}]},{"type":"paragraph","content":[{"type":"text","text":"Anything that moved more than expected, and why.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Variance and explanation]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Outlook"}]},{"type":"paragraph","content":[{"type":"text","text":"What you expect next period, and any risks to that outlook.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Outlook.]"}]}]}'::jsonb,
  metadata = '{"document_type":"financial_report","category":"professional","use_cases":["Board reporting","Investor updates","Internal finance reviews"],"supported_views":["dashboard","calendar","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"report_period","field_label":"Report period","field_type":"text","ai_fill_enabled":true},{"field_key":"report_type","field_label":"Report type","field_type":"select","options":["p_and_l","balance_sheet","cash_flow","budget_vs_actual"],"ai_fill_enabled":true},{"field_key":"currency","field_label":"Currency","field_type":"text","ai_fill_enabled":false}],"default_properties":{"status":"draft"}}'::jsonb
where slug = 'financial-report'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Research Paper',
  description = 'Abstract, related work, methodology, results, discussion, and references',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Abstract"}]},{"type":"paragraph","content":[{"type":"text","text":"The whole paper in 150-250 words — problem, method, key result.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Abstract.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Introduction"}]},{"type":"paragraph","content":[{"type":"text","text":"The gap in existing knowledge this paper addresses.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Introduction.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Related Work & Literature Review"}]},{"type":"paragraph","content":[{"type":"text","text":"Place this work in the current research discourse — prior art and how you differ.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Related work.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Methodology"}]},{"type":"paragraph","content":[{"type":"text","text":"How the research was conducted, in enough detail to replicate.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Methodology.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Results"}]},{"type":"paragraph","content":[{"type":"text","text":"What was found — data and observations, without interpretation yet.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Results.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Discussion"}]},{"type":"paragraph","content":[{"type":"text","text":"What the results mean and their implications. Explicitly disclose study limitations — peer reviewers expect this.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Discussion.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"References"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source cited, formatted per the target venue''s style.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Reference]"}]}]}]}]}'::jsonb,
  metadata = '{"document_type":"research_paper","category":"professional","use_cases":["Journal submissions","Conference papers","Preprints"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"paper_status","field_label":"Paper status","field_type":"status","options":[{"value":"drafting","label":"Drafting","category":"unstarted"},{"value":"under_review","label":"Under review","category":"started"},{"value":"revision","label":"Revision","category":"started"},{"value":"accepted","label":"Accepted","category":"completed"},{"value":"published","label":"Published","category":"completed"}],"ai_fill_enabled":true},{"field_key":"journal_or_venue","field_label":"Journal / venue","field_type":"text","ai_fill_enabled":true},{"field_key":"citation_style","field_label":"Citation style","field_type":"select","options":["apa","mla","chicago","ieee"],"ai_fill_enabled":true}],"default_properties":{"status":"draft","paper_status":"drafting"}}'::jsonb
where slug = 'research-paper'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Thesis',
  description = 'Abstract, research question, literature review, methodology, findings, and defense prep',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Abstract"}]},{"type":"paragraph","content":[{"type":"text","text":"The thesis in miniature — question, method, and conclusion.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Abstract.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Introduction & Research Question"}]},{"type":"paragraph","content":[{"type":"text","text":"Why this question matters, and precisely what it is.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Introduction and research question.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Literature Review"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s already known, and where this thesis fits. Use H3/H4 subheadings to chapter long sections.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Literature review.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Methodology"}]},{"type":"paragraph","content":[{"type":"text","text":"How the research question was investigated. Use H3/H4 for chapter structure.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Methodology.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Findings"}]},{"type":"paragraph","content":[{"type":"text","text":"What the research revealed. Use H3/H4 for chapter structure.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Findings.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Conclusion & Future Work"}]},{"type":"paragraph","content":[{"type":"text","text":"What this means, and what''s left to explore.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Conclusion and future work.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Defense Notes & Q&A Prep"}]},{"type":"paragraph","content":[{"type":"text","text":"Likely examiner questions, counterarguments, and your prepared responses.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Question / counterargument] — [Response]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"References"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source cited.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Reference]"}]}]}]}]}'::jsonb,
  metadata = '{"document_type":"thesis","category":"professional","use_cases":["Bachelor thesis","Master thesis","PhD dissertations"],"supported_views":["wiki","kanban","gantt"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"thesis_level","field_label":"Thesis level","field_type":"select","options":["bachelor","master","phd"],"ai_fill_enabled":true},{"field_key":"thesis_status","field_label":"Thesis status","field_type":"status","options":[{"value":"proposal","label":"Proposal","category":"unstarted"},{"value":"writing","label":"Writing","category":"started"},{"value":"review","label":"Review","category":"started"},{"value":"defense_scheduled","label":"Defense scheduled","category":"started"},{"value":"completed","label":"Completed","category":"completed"}],"ai_fill_enabled":true},{"field_key":"advisor","field_label":"Advisor","field_type":"relation","ai_fill_enabled":false},{"field_key":"defense_date","field_label":"Defense date","field_type":"date","ai_fill_enabled":true},{"field_key":"citation_style","field_label":"Citation style","field_type":"select","options":["apa","mla","chicago","ieee"],"ai_fill_enabled":true}],"default_properties":{"status":"draft","thesis_level":"bachelor","thesis_status":"proposal"}}'::jsonb
where slug = 'thesis'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Student Essay',
  description = 'Thesis statement, argument, counterarguments, and conclusion',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Thesis Statement"}]},{"type":"paragraph","content":[{"type":"text","text":"The single claim this essay argues for, in one sentence.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Thesis statement.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Body Paragraphs / Argument"}]},{"type":"paragraph","content":[{"type":"text","text":"Outline body paragraphs as bullets first, then expand into prose — that prevents blank-page block.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Argument and evidence.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Counterarguments"}]},{"type":"paragraph","content":[{"type":"text","text":"The strongest objection to your thesis, and your response to it.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Counterargument and response.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Conclusion"}]},{"type":"paragraph","content":[{"type":"text","text":"Restate the thesis in light of the argument, and its wider significance.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Conclusion.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"References"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source cited.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Reference]"}]}]}]}]}'::jsonb,
  metadata = '{"document_type":"student_essay","category":"professional","use_cases":["Coursework essays","Argumentative writing","Exam preparation"],"supported_views":["wiki","calendar"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"course","field_label":"Course","field_type":"text","ai_fill_enabled":true},{"field_key":"word_count_target","field_label":"Word count target","field_type":"number","ai_fill_enabled":false},{"field_key":"essay_status","field_label":"Essay status","field_type":"status","options":[{"value":"outline","label":"Outline","category":"unstarted"},{"value":"drafting","label":"Drafting","category":"started"},{"value":"revising","label":"Revising","category":"started"},{"value":"submitted","label":"Submitted","category":"completed"}],"ai_fill_enabled":true}],"default_properties":{"status":"draft","essay_status":"outline"}}'::jsonb
where slug = 'student-essay'
  and coalesce(is_system, false) = true
  and workspace_id is null;

update templates
set
  name = 'Literature Review',
  description = 'Sources reviewed, synthesis of themes, and gaps in the literature',
  structure_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Research Question / Scope"}]},{"type":"paragraph","content":[{"type":"text","text":"Document exact search strings, databases (Scholar, IEEE, Scopus), and inclusion/exclusion criteria so the review is replicable.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Research question and scope.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Sources Reviewed"}]},{"type":"paragraph","content":[{"type":"text","text":"Every source, with its key finding and relevance to your question.","marks":[{"type":"italic"}]}]},{"type":"table","content":[{"type":"tableRow","content":[{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Source"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Key Findings"}]}]},{"type":"tableHeader","content":[{"type":"paragraph","content":[{"type":"text","text":"Relevance"}]}]}]},{"type":"tableRow","content":[{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Source]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Key finding]"}]}]},{"type":"tableCell","content":[{"type":"paragraph","content":[{"type":"text","text":"[Relevance]"}]}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Synthesis & Themes"}]},{"type":"paragraph","content":[{"type":"text","text":"The patterns and disagreements across sources — not a list, a synthesis.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Synthesis and themes.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Gaps in Literature"}]},{"type":"paragraph","content":[{"type":"text","text":"What''s missing — this is often where your own research question lives.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Gap]"}]}]}]}]}'::jsonb,
  metadata = '{"document_type":"literature_review","category":"professional","use_cases":["Thesis background chapters","Systematic reviews","Research proposals"],"supported_views":["wiki","kanban"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"research_area","field_label":"Research area","field_type":"select","options":["ai_ml","ux_strategy","growth_economics","product","security","other"],"ai_fill_enabled":true},{"field_key":"review_status","field_label":"Review status","field_type":"status","options":[{"value":"scoping","label":"Scoping","category":"unstarted"},{"value":"reviewing","label":"Reviewing","category":"started"},{"value":"synthesizing","label":"Synthesizing","category":"started"},{"value":"complete","label":"Complete","category":"completed"}],"ai_fill_enabled":true},{"field_key":"citation_style","field_label":"Citation style","field_type":"select","options":["apa","mla","chicago","ieee"],"ai_fill_enabled":true}],"default_properties":{"status":"draft","review_status":"scoping"}}'::jsonb
where slug = 'literature-review'
  and coalesce(is_system, false) = true
  and workspace_id is null;

insert into templates (name, description, structure_json, is_system, is_shared, slug, metadata)
select
  'Ticket',
  'Lightweight work item for Kanban — context, acceptance criteria, and notes',
  '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Context"}]},{"type":"paragraph","content":[{"type":"text","text":"What needs doing, why it matters, and any links (bug report, brief, PRD). Keep this short — the board card is the unit of work.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Context.]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Acceptance Criteria"}]},{"type":"paragraph","content":[{"type":"text","text":"Done-when conditions. Prefer checkable bullets so reviewers share one definition of done.","marks":[{"type":"italic"}]}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Criterion]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Criterion]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Notes & Links"}]},{"type":"paragraph","content":[{"type":"text","text":"Implementation notes, screenshots, or links to PRs and related docs.","marks":[{"type":"italic"}]}]},{"type":"paragraph","content":[{"type":"text","text":"[Notes.]"}]}]}'::jsonb,
  true,
  true,
  'ticket',
  '{"document_type":"ticket","category":"essentials","use_cases":["Engineering backlog tickets","Marketing task cards","Ops / support work items"],"supported_views":["kanban","calendar","gantt","wiki"],"schema_fields":[{"field_key":"status","field_label":"Status","field_type":"select","options":["draft","in_progress","done"],"ai_fill_enabled":true},{"field_key":"due_date","field_label":"Due","field_type":"date","ai_fill_enabled":true},{"field_key":"owner","field_label":"Owner","field_type":"text","ai_fill_enabled":true},{"field_key":"summary","field_label":"Summary","field_type":"textarea","ai_fill_enabled":true},{"field_key":"origin","field_label":"Origin","field_type":"relation","ai_fill_enabled":false},{"field_key":"priority","field_label":"Priority","field_type":"select","options":["urgent","high","medium","low"],"ai_fill_enabled":true},{"field_key":"ticket_type","field_label":"Ticket type","field_type":"select","options":["task","bug","chore","request","spike"],"ai_fill_enabled":true}],"default_properties":{"status":"draft","priority":"medium","ticket_type":"task"}}'::jsonb
where not exists (
  select 1 from templates
  where slug = 'ticket'
    and coalesce(is_system, false) = true
    and workspace_id is null
);

-- Promote person/org text fields to relation where they already exist.
update metadata_schemas
set field_type = 'relation', ai_fill_enabled = false
where field_key in ('employee', 'manager', 'participant', 'recipient', 'counterparty', 'advisor')
  and field_type = 'text';

-- Jurisdiction: text → select (options may already be set by seed).
update metadata_schemas
set field_type = 'select',
    options = coalesce(options, '["DE","EU","US","UK","other"]'::jsonb)
where field_key = 'jurisdiction'
  and field_type = 'text';

-- Department / research_area: text → select when present.
update metadata_schemas
set field_type = 'select',
    options = coalesce(options, '["engineering","product","marketing","operations","leadership","other"]'::jsonb)
where field_key = 'department'
  and field_type = 'text';

update metadata_schemas
set field_type = 'select',
    options = coalesce(
      options,
      '["ai_ml","ux_strategy","growth_economics","product","security","other"]'::jsonb
    )
where field_key = 'research_area'
  and field_type = 'text';

insert into metadata_schemas (workspace_id, field_key, field_label, field_type, options, ai_fill_enabled)
select ms.workspace_id, v.field_key, v.field_label, v.field_type, v.options, v.ai_fill_enabled
from (
  select distinct workspace_id from metadata_schemas
  where field_key in (
    'letter_type', 'requires_hr_followup', 'pdp_status', 'seniority', 'review_status',
    'legal_status', 'compliance_status', 'report_type', 'paper_status', 'thesis_status',
    'essay_status', 'citation_style', 'status'
  )
) ms
cross join (
  values
    ('subject_line', 'Subject line', 'text', null::jsonb, true),
    ('visibility', 'Visibility', 'select', '["private","managers","hr"]'::jsonb, false),
    ('related_audit', 'Related audit', 'relation', null::jsonb, false),
    ('priority', 'Priority', 'select', '["urgent","high","medium","low"]'::jsonb, true),
    ('ticket_type', 'Ticket type', 'select', '["task","bug","chore","request","spike"]'::jsonb, true),
    ('manager', 'Manager', 'relation', null::jsonb, false),
    ('counterparty', 'Counterparty', 'relation', null::jsonb, false)
) as v(field_key, field_label, field_type, options, ai_fill_enabled)
where not exists (
  select 1 from metadata_schemas e
  where e.workspace_id = ms.workspace_id and e.field_key = v.field_key
);
